<a href="https://colab.research.google.com/github/2003saurabh/deep_learning/blob/main/embedding_encoding_simpleRNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [16]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [17]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [18]:
tokenizer.fit_on_texts(docs)

In [19]:
len(tokenizer.word_index)

17

In [28]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [20]:
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [29]:
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [30]:
model=Sequential()

model.add(Embedding(17,output_dim=2,input_length=5))
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.compile('adam','accuracy')

In [32]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 574ms/step
[[[ 0.01645956  0.0066957 ]
  [-0.04394237 -0.0297082 ]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]]

 [[-0.04394237 -0.0297082 ]
  [-0.04394237 -0.0297082 ]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]]

 [[-0.01438353  0.03731451]
  [-0.01438353  0.03731451]
  [ 0.01154771 -0.04765452]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]]

 [[ 0.0253746  -0.00081202]
  [-0.03230461  0.03813202]
  [ 0.0253746  -0.00081202]
  [-0.04394237 -0.0297082 ]
  [ 0.0253746  -0.00081202]]

 [[ 0.0432814   0.00251605]
  [ 0.00146578  0.02777574]
  [ 0.04642126  0.03549946]
  [ 0.01583997 -0.03541355]
  [ 0.01318819  0.0233462 ]]

 [[-0.03321928 -0.00020526]
  [-0.03321928 -0.00020526]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462 ]]

 [[-0.00499789  0.02329795]
  [-0.00499789  0.02329795]
  [ 0.01318819  0.0233462 ]
  [ 0.01318819  0.0233462

In [33]:
from keras.datasets import imdb

In [34]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [35]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [36]:
X_train.shape

(25000, 50)

In [38]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - acc: 0.5306 - loss: 0.6841 - val_acc: 0.7908 - val_loss: 0.4597
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - acc: 0.8139 - loss: 0.4169 - val_acc: 0.8056 - val_loss: 0.4349
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - acc: 0.8620 - loss: 0.3372 - val_acc: 0.7975 - val_loss: 0.4531
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - acc: 0.8721 - loss: 0.3133 - val_acc: 0.7869 - val_loss: 0.4716
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - acc: 0.8744 - loss: 0.3076 - val_acc: 0.7873 - val_loss: 0.4795
